##Departmental and university service

##Pitt
- title: Standard Research Workstation pilot
  description: Participated in pilot program through Pitt Research and Pitt IT to test virtual machines for mid-scale research computing
  category: departmental and university
  university: University of Pittsburgh
  startdate: May 2022
  enddate: present

- title: Pitt Data Science in Graduate Programs initiative
  description: Participated in a data science summit and further meetings with faculty across the Dietrich School of Arts and Sciences about promoting data science in graduate programs at Pitt
  category: departmental and university
  university: University of Pittsburgh
  startdate: May 2022
  enddate: present

- title: "Careers in language data: How to prepare our language students for the data-focused job future"
  role: co-chair
  description: Hosted symposium on career opportunities in the tech industry for linguistics students, in conjunction with Pitt's Year of Data and Society
  category: departmental and university
  university: University of Pittsburgh
  startdate: December 2021
  enddate: April 2022
  url: https://www.linguistics.pittedu/event/careers-language-data-symposium 

- title: Computational Linguistics joint degree program committee
  description: Worked with faculty and leadership from Linguistics, Computer Science, and Arts & Sciences to design a joint certificate program in Computational Linguistics
  category: departmental and university
  university: University of Pittsburgh
  startdate: August 2020
  enddate: present

##UC Davis
- title: Committee on Courses of Instruction
  description: Graduate Student Association representative on Faculty Senate committee charged with approving new/revised course proposals and program/policy changes affecting instruction
  category: departmental and university
  university: University of California, Davis
  startdate: April 2012
  enddate: March 2016

- title: Teaching Assistant Consultant
  description: Participated in Center for Excellence in Teaching and Learning program to learn about effective instruction, lead peer consultations to help graduate students improve their teaching, and facilitate Teaching Assistant Orientation and other workshops for graduate students
  category: departmental and university
  university: University of California, Davis
  startdate: March 2015
  enddate: March 2016
 
- title: Professors for the Future
  description: Participated in Graduate Studies program to learn about professional development, take a seminar on college teaching, and conduct a workshop series to facilitate cross-cultural communication between international graduate student instructors and undergraduate students
  category: departmental and university
  university: University of California, Davis
  startdate: September 2013
  enddate: June 2014

- title: Linguistics Graduate Student Association
  description: Led a committee of Linguistics graduate students to formally organize a representative group, including passing a formal set of governing guidelines; served as Facilitator to coordinate activities of the Linguistics Graduate Student Association and be a mentor to first-year graduate students; served as Executive Committee Representative to represent interests of Linguistics graduate students to Linguistics faculty
  category: departmental and university
  university: University of California, Davis
  startdate: March 2012
  enddate: September 2015

- title: Graduate Student Association
  description: Served as Linguistics department representative to university-wide GSA
  category: departmental and university
  university: University of California, Davis
  startdate: September 2010
  enddate: June 2012

- title: International Graduate Student Orientation
  description: Led “Communicating across Language and Cultural Differences” workshops for new international graduate students
  category: departmental and university
  university: University of California, Davis
  date: September 2014

- title: Graduate Research Advocacy Day
  description: Met with California state legislative staffs regarding the importance of graduate research to the University of California
  category: departmental and university
  university: University of California, Davis
  date: June 2013


##Service to the profession
- committee: Committee on Scholarly Communication in Linguistics
  organization: Linguistic Society of America
  category: committee
  startdate: August 2021
  enddate: present

- agency: National Science Foundation
  category: grant review
  dates: 2021

- agency: Deutsche Forschungsgemeinschaft (German Research Foundation)
  category: grant review
  dates: 2021

- journal: TESOL Quarterly
  category: article review
  dates: 2012

- journal: Journal of English Linguistics
  category: article review
  dates: 2019

- journal: Socius
  category: article review
  dates: 2020

- journal: Language and Speech
  category: article review
  dates: 2023

- conference: Linguistic Society of America
  category: abstract review
  dates: [2019, 2020, 2021]

- conference: American Dialect Society
  category: abstract review
  dates: [2015]

- conference: New Ways of Analyzing Variation
  category: abstract review
  dates: [2018, 2019]

- degree: Masters of Research in Linguistics
  university: Macquarie University
  category: external thesis examination
  dates: 2020

